load("stdlib.moon")

# ── math ──────────────────────────────────────────────────────────────────────
assert_eq(min(3, 7),          3,    "min")
assert_eq(max(3, 7),          7,    "max")
assert_eq(clamp(15, 0, 10),   10,   "clamp hi")
assert_eq(clamp(-5, 0, 10),   0,    "clamp lo")
assert_eq(clamp(5,  0, 10),   5,    "clamp mid")
assert_eq(sign(-99),          -1,   "sign neg")
assert_eq(sign(0),            0,    "sign zero")
assert_eq(sign(42),           1,    "sign pos")
assert_eq(round(3.4),         3,    "round down")
assert_eq(round(3.5),         4,    "round up")
assert_eq(round_to(3.14159, 2), 3.14, "round_to")
assert_eq(mod(17, 5),         2,    "mod")
assert_eq(mod(-1, 5),         4,    "mod negative")
assert_eq(even(4),            1,    "even")
assert_eq(odd(7),             1,    "odd")
assert_eq(gcd(48, 18),        6,    "gcd")
assert_eq(lcm(4, 6),          12,   "lcm")
assert_eq(ipow(2, 10),        1024, "ipow")
assert_eq(lerp(0, 10, 0.5),   5,    "lerp")
assert_eq(map_range(5, 0, 10, 0, 100), 50, "map_range")
assert_eq(round_to(deg2rad(180), 5), round_to(PI, 5), "deg2rad")

# ── string ────────────────────────────────────────────────────────────────────
assert_eq(pad_left("7",  3, "0"),    "007",    "pad_left")
assert_eq(pad_right("hi", 5, "."),   "hi...",  "pad_right")
assert_eq(trim("  hello  "),         "hello",  "trim")
assert_eq(ltrim("  hi"),             "hi",     "ltrim")
assert_eq(rtrim("hi   "),            "hi",     "rtrim")
assert_eq(starts_with("moon", "mo"), 1,        "starts_with yes")
assert_eq(starts_with("moon", "on"), 0,        "starts_with no")
assert_eq(ends_with("moon", "on"),   1,        "ends_with yes")
assert_eq(ends_with("moon", "mo"),   0,        "ends_with no")
assert_eq(count_str("abcabc", "bc"), 2,        "count_str")
assert_eq(replace("hello", "l", "r"), "herro", "replace")
assert_eq(replace("aaa", "a", "bb"), "bbbbbb", "replace expand")
assert_eq(repeat_str("ha", 3),       "hahaha", "repeat_str")
assert_eq(fmt_fixed(3.14159, 2),     "3.14",   "fmt_fixed")
assert_eq(fmt_fixed(-0.5, 1),        "-0.5",   "fmt_fixed neg")
assert_eq(fmt_fixed(10, 0),          "10",    "fmt_fixed 0 dec")

# ── arrays ────────────────────────────────────────────────────────────────────
var a = arr_make()
a = arr_push(a, 10)
a = arr_push(a, 20)
a = arr_push(a, 30)
assert_eq(arr_len(a),       3,    "arr_len")
assert_eq(arr_get(a, 0),    "10", "arr_get 0")
assert_eq(arr_get(a, 2),    "30", "arr_get 2")
a = arr_set(a, 1, 99)
assert_eq(arr_get(a, 1),    "99", "arr_set")
assert_eq(arr_sum(a),       139,  "arr_sum")
assert_eq(arr_mean(a),      139/3, "arr_mean")
assert_eq(arr_min(a),       10,   "arr_min")
assert_eq(arr_max(a),       99,   "arr_max")

var r = arr_range(0, 5, 1)
assert_eq(arr_len(r),       5,    "arr_range len")
assert_eq(arr_get(r, 4),    "4",  "arr_range last")
assert_eq(arr_sum(r),       10,   "arr_range sum")

# sort
var s = arr_make()
s = arr_push(s, 5)
s = arr_push(s, 1)
s = arr_push(s, 4)
s = arr_push(s, 2)
s = arr_sort(s)
assert_eq(arr_get(s, 0), "1", "sort[0]")
assert_eq(arr_get(s, 1), "2", "sort[1]")
assert_eq(arr_get(s, 2), "4", "sort[2]")
assert_eq(arr_get(s, 3), "5", "sort[3]")

# split / join
var parts = split("a,b,c,d", ",")
assert_eq(arr_len(parts),   4,   "split len")
assert_eq(arr_get(parts, 0),"a", "split[0]")
assert_eq(arr_get(parts, 3),"d", "split[3]")
assert_eq(join(parts, "-"), "a-b-c-d", "join")

# stats
var data = arr_make()
data = arr_push(data, 2)
data = arr_push(data, 4)
data = arr_push(data, 4)
data = arr_push(data, 4)
data = arr_push(data, 5)
data = arr_push(data, 5)
data = arr_push(data, 7)
data = arr_push(data, 9)
assert_eq(arr_mean(data), 5, "mean")
assert_eq(arr_std(data),  2, "std dev")

test_summary()
