load("stdlib.moon")

# ── Constants ─────────────────────────────────────────────────────────────────
assert_eq(round_to(PI,  5), 3.14159, "PI")
assert_eq(round_to(E,   4), 2.7183,  "E")
assert_eq(round_to(PHI, 4), 1.618,   "PHI")

# ── Core math ─────────────────────────────────────────────────────────────────
assert_eq(min(3, 7),             3,    "min")
assert_eq(max(3, 7),             7,    "max")
assert_eq(clamp(15, 0, 10),      10,   "clamp hi")
assert_eq(clamp(-5, 0, 10),      0,    "clamp lo")
assert_eq(clamp(5,  0, 10),      5,    "clamp mid")
assert_eq(sign(-99),             -1,   "sign neg")
assert_eq(sign(0),               0,    "sign zero")
assert_eq(sign(42),              1,    "sign pos")
assert_eq(round(3.4),            3,    "round down")
assert_eq(round(3.5),            4,    "round up")
assert_eq(round_to(3.14159, 2),  3.14, "round_to")
assert_eq(mod(17, 5),            2,    "mod positive")
assert_eq(mod(-1, 5),            4,    "mod negative")
assert_eq(even(4),               1,    "even true")
assert_eq(even(3),               0,    "even false")
assert_eq(odd(7),                1,    "odd true")
assert_eq(odd(2),                0,    "odd false")
assert_eq(gcd(48, 18),           6,    "gcd")
assert_eq(lcm(4, 6),             12,   "lcm")
assert_eq(ipow(2, 10),           1024, "ipow")
assert_eq(lerp(0, 10, 0.5),      5,    "lerp mid")
assert_eq(lerp(0, 10, 0),        0,    "lerp start")
assert_eq(lerp(0, 10, 1),        10,   "lerp end")
assert_eq(map_range(5, 0, 10, 0, 100), 50, "map_range mid")
assert_eq(map_range(0, 0, 10, 0, 100), 0,  "map_range lo")
assert_eq(round_to(deg2rad(180), 5), round_to(PI, 5), "deg2rad(180)=PI")
assert_eq(rad2deg(PI),           180,  "rad2deg(PI)=180")

# ── Number formatting ─────────────────────────────────────────────────────────
assert_eq(pad_left("7",   3, "0"),  "007",   "pad_left")
assert_eq(pad_left("42",  3, "0"),  "042",   "pad_left partial")
assert_eq(pad_left("123", 3, "0"),  "123",   "pad_left already wide")
assert_eq(pad_right("hi", 5, "."),  "hi...", "pad_right")
assert_eq(fmt_fixed(3.14159, 2),    "3.14",  "fmt_fixed 2dp")
assert_eq(fmt_fixed(3.14159, 0),    "3",     "fmt_fixed 0dp")
assert_eq(fmt_fixed(-2.5, 1),       "-2.5",  "fmt_fixed negative")
assert_eq(fmt_fixed(0.5, 0),        "1",     "fmt_fixed rounds up")
assert_eq(fmt_fixed(10, 2),         "10.00", "fmt_fixed integer to 2dp")

# ── String utilities ──────────────────────────────────────────────────────────
assert_eq(starts_with("moon", "mo"),  1,        "starts_with yes")
assert_eq(starts_with("moon", "on"),  0,        "starts_with no")
assert_eq(starts_with("moon", "moon"),1,        "starts_with full match")
assert_eq(starts_with("hi", "hello"), 0,        "starts_with prefix longer than s")
assert_eq(ends_with("moon", "on"),    1,        "ends_with yes")
assert_eq(ends_with("moon", "mo"),    0,        "ends_with no")
assert_eq(ends_with("moon", "moon"),  1,        "ends_with full match")
assert_eq(trim("  hello  "),          "hello",  "trim both sides")
assert_eq(trim("hello"),              "hello",  "trim nothing to do")
assert_eq(ltrim("  hi"),              "hi",     "ltrim")
assert_eq(rtrim("hi   "),             "hi",     "rtrim")
assert_eq(repeat_str("ha", 3),        "hahaha", "repeat_str")
assert_eq(repeat_str("x", 1),        "x",      "repeat_str once")
assert_eq(repeat_str("x", 0),        "",       "repeat_str zero")
assert_eq(count_str("abcabc", "bc"),  2,        "count_str")
assert_eq(count_str("aaaa", "aa"),    2,        "count_str non-overlapping")
assert_eq(count_str("hello", "x"),    0,        "count_str not found")
assert_eq(replace("hello", "l", "r"), "herro",  "replace all occurrences")
assert_eq(replace("aaa", "a", "bb"), "bbbbbb",  "replace expanding")
assert_eq(replace("hello", "x", "y"),"hello",   "replace not found")

# ── Array algorithms (testing stdlib procs, not array mechanics) ───────────────
var nums = [2, 4, 4, 4, 5, 5, 7, 9]

assert_eq(arr_sum(nums),      40,  "arr_sum")
assert_eq(arr_min(nums),      2,   "arr_min")
assert_eq(arr_max(nums),      9,   "arr_max")
assert_eq(arr_contains(nums, 7),  1, "arr_contains found")
assert_eq(arr_contains(nums, 0),  0, "arr_contains not found")

var rev = arr_reverse(nums)
assert_eq(rev[0],   9, "arr_reverse: first element")
assert_eq(rev[-1],  2, "arr_reverse: last element")
assert_eq(nums[0],  2, "arr_reverse: original unchanged")

var sorted = arr_sort([5, 3, 8, 1, 9, 2, 7, 4, 6])
assert_eq(sorted[0],  1, "arr_sort: first")
assert_eq(sorted[4],  5, "arr_sort: middle")
assert_eq(sorted[-1], 9, "arr_sort: last")

assert_eq(arr_sum(range(1, 101)), 5050, "arr_sum(range(1,101))")

test_summary()
